// Aggregator for active-city spots.
//
// MVP: only Japan cities (tokyo/osaka/kyoto/fukuoka) are imported so their spots
// ship in the client bundle. The other 23 city files are kept on disk for when
// we activate additional countries (see destinations.ts / comingSoonCountries) —
// add them back to the import list and `allSpots` when that happens.
//
// `data/spots/<city>.ts` is generated by scripts/extract-spots-from-courses.ts.

import type { Spot } from "@/types/spot";

import { tokyoSpots } from "./tokyo";
import { osakaSpots } from "./osaka";
import { kyotoSpots } from "./kyoto";
import { fukuokaSpots } from "./fukuoka";

export const allSpots: Spot[] = [
  ...tokyoSpots,
  ...osakaSpots,
  ...kyotoSpots,
  ...fukuokaSpots,
];

export function getSpotsByCity(city: string): Spot[] {
  return allSpots.filter((s) => s.city === city);
}

export function getSpotById(id: string): Spot | undefined {
  return allSpots.find((s) => s.id === id);
}
