"use client";

import { FileDown } from "lucide-react";
import type { Locale, GeneratedDay } from "@/types";
import { countries } from "@/data/destinations";

interface DownloadPDFButtonProps {
  locale: Locale;
  days: GeneratedDay[];
  duration: string;
}

export function DownloadPDFButton({ locale, days, duration }: DownloadPDFButtonProps) {

  function handlePrint() {
    const allCities = countries.flatMap((c) => c.cities);
    const cityNames = [...new Set(days.map((d) => {
      const city = allCities.find((c) => c.id === d.city);
      return city?.label[locale] ?? d.city;
    }))].join(" + ");

    const title = locale === "ko"
      ? `${cityNames} ${duration}박${Number(duration) + 1}일 여행 일정`
      : `${cityNames} ${Number(duration) + 1}-Day Itinerary`;

    // Build printable HTML
    let html = `<!DOCTYPE html><html><head><meta charset="utf-8">
      <title>${title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, "Malgun Gothic", "맑은 고딕", sans-serif; color: #1a1a1a; padding: 40px; max-width: 800px; margin: 0 auto; font-size: 14px; line-height: 1.7; }
        h1 { font-size: 22px; margin-bottom: 4px; }
        .subtitle { color: #999; font-size: 11px; margin-bottom: 24px; }
        .divider { border: none; border-top: 1px solid #eee; margin: 20px 0; }
        .day-header { display: flex; align-items: center; gap: 10px; margin-bottom: 4px; }
        .day-num { background: #2563EB; color: white; font-weight: 700; font-size: 12px; width: 28px; height: 28px; border-radius: 8px; display: flex; align-items: center; justify-content: center; }
        .day-title { font-size: 16px; font-weight: 700; }
        .day-city { color: #aaa; font-size: 11px; margin-bottom: 12px; }
        .activity { margin-bottom: 10px; padding-left: 12px; }
        .act-time { font-weight: 700; color: #444; font-size: 13px; }
        .act-title { font-weight: 700; font-size: 13px; }
        .act-desc { color: #666; font-size: 12px; }
        .tip { color: #b45309; font-size: 11px; margin-top: 2px; }
        .cost-row { background: #f9fafb; padding: 8px 12px; border-radius: 8px; font-size: 11px; color: #666; margin-top: 8px; }
        .footer { color: #ccc; font-size: 10px; margin-top: 32px; text-align: center; }
        @media print { body { padding: 20px; } .no-print { display: none; } }
      </style>
    </head><body>`;

    html += `<h1>${title}</h1>`;
    html += `<p class="subtitle">Tripflowy — tripflowy.com</p>`;
    html += `<hr class="divider">`;

    for (const day of days) {
      const cityLabel = allCities.find((c) => c.id === day.city)?.label[locale] ?? day.city;
      html += `<div style="margin-bottom: 28px;">`;
      html += `<div class="day-header"><div class="day-num">${day.dayNumber}</div><div class="day-title">${day.course.title[locale]}</div></div>`;
      html += `<div class="day-city">${cityLabel}</div>`;

      for (const act of day.course.activities) {
        html += `<div class="activity">`;
        html += `<span class="act-time">${act.time}</span> <span class="act-title">${act.title[locale]}</span><br>`;
        html += `<span class="act-desc">${act.description[locale]}</span>`;
        if (act.tips) {
          for (const tip of act.tips) {
            html += `<div class="tip">💡 ${tip[locale]}</div>`;
          }
        }
        html += `</div>`;
      }

      if (day.course.costs) {
        const c = day.course.costs;
        const costText = locale === "ko"
          ? `식비 ${c.food.toLocaleString()}원 · 투어 ${c.activity.toLocaleString()}원 · 교통 ${c.transport.toLocaleString()}원 · 기타 ${c.etc.toLocaleString()}원`
          : `Food ${c.food} · Tour ${c.activity} · Transport ${c.transport} · Etc ${c.etc} (${c.currency})`;
        html += `<div class="cost-row">${costText}</div>`;
      }

      html += `</div><hr class="divider">`;
    }

    html += `<p class="footer">Generated by Tripflowy — tripflowy.com</p>`;
    html += `</body></html>`;

    // Open print window
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
      };
    }
  }

  return (
    <button
      onClick={handlePrint}
      className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 transition-colors"
    >
      <FileDown className="w-4 h-4" />
      {locale === "ko" ? "PDF 다운로드" : "Download PDF"}
    </button>
  );
}
