"use client";

import { useState } from "react";
import { FileDown, Loader2 } from "lucide-react";
import type { Locale, GeneratedDay } from "@/types";
import { countries } from "@/data/destinations";

interface DownloadPDFButtonProps {
  locale: Locale;
  days: GeneratedDay[];
  duration: string;
}

export function DownloadPDFButton({ locale, days, duration }: DownloadPDFButtonProps) {
  const [loading, setLoading] = useState(false);

  async function handleDownload() {
    setLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const allCities = countries.flatMap((c) => c.cities);

      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 15;
      const contentWidth = pageWidth - margin * 2;
      let y = 20;

      // Title
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      const cityNames = [...new Set(days.map((d) => {
        const city = allCities.find((c) => c.id === d.city);
        return city?.label[locale] ?? d.city;
      }))].join(" + ");
      const title = locale === "ko"
        ? `${cityNames} ${duration}박${Number(duration) + 1}일 여행 일정`
        : `${cityNames} ${Number(duration) + 1}-Day Itinerary`;
      doc.text(title, margin, y);
      y += 10;

      // Subtitle
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 120, 120);
      doc.text(`Tripflowy — tripflowy.com`, margin, y);
      y += 10;

      doc.setDrawColor(230, 230, 230);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;

      // Days
      for (const day of days) {
        // Check page overflow
        if (y > 260) {
          doc.addPage();
          y = 20;
        }

        const cityLabel = allCities.find((c) => c.id === day.city)?.label[locale] ?? day.city;

        // Day header
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(37, 99, 235); // blue
        doc.text(`Day ${day.dayNumber}`, margin, y);
        doc.setTextColor(30, 30, 30);
        doc.text(`  ${day.course.title[locale]}`, margin + 18, y);
        y += 5;

        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text(cityLabel, margin, y);
        y += 6;

        // Activities
        for (const act of day.course.activities) {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }

          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(60, 60, 60);
          doc.text(`${act.time}  ${act.title[locale]}`, margin + 2, y);
          y += 5;

          doc.setFont("helvetica", "normal");
          doc.setFontSize(9);
          doc.setTextColor(100, 100, 100);
          const descLines = doc.splitTextToSize(act.description[locale], contentWidth - 10);
          doc.text(descLines, margin + 4, y);
          y += descLines.length * 4 + 2;

          // Tips
          if (act.tips) {
            for (const tip of act.tips) {
              if (y > 270) { doc.addPage(); y = 20; }
              doc.setTextColor(180, 120, 0);
              doc.setFontSize(8);
              const tipLines = doc.splitTextToSize(`💡 ${tip[locale]}`, contentWidth - 12);
              doc.text(tipLines, margin + 6, y);
              y += tipLines.length * 3.5 + 1;
            }
          }
          y += 2;
        }

        // Cost summary
        if (day.course.costs) {
          if (y > 265) { doc.addPage(); y = 20; }
          doc.setFontSize(8);
          doc.setTextColor(100, 100, 100);
          const c = day.course.costs;
          const costText = locale === "ko"
            ? `식비 ${c.food.toLocaleString()}${c.currency === "KRW" ? "원" : c.currency} | 투어 ${c.activity.toLocaleString()} | 교통 ${c.transport.toLocaleString()} | 기타 ${c.etc.toLocaleString()}`
            : `Food ${c.food} | Tour ${c.activity} | Transport ${c.transport} | Etc ${c.etc} (${c.currency})`;
          doc.text(costText, margin, y);
          y += 6;
        }

        // Divider
        doc.setDrawColor(240, 240, 240);
        doc.line(margin, y, pageWidth - margin, y);
        y += 8;
      }

      // Footer
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setFontSize(8);
      doc.setTextColor(180, 180, 180);
      doc.text(`Generated by Tripflowy — tripflowy.com`, margin, y);

      // Save
      const filename = locale === "ko"
        ? `${cityNames}_${duration}박${Number(duration) + 1}일_여행일정.pdf`
        : `${cityNames}_${Number(duration) + 1}day_itinerary.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setLoading(false);
    }
  }

  return (
    <button
      onClick={handleDownload}
      disabled={loading}
      className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 transition-colors disabled:opacity-50"
    >
      {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
      {loading
        ? (locale === "ko" ? "PDF 생성 중..." : "Generating...")
        : (locale === "ko" ? "PDF 다운로드" : "Download PDF")}
    </button>
  );
}
